#pragma once

using namespace ATL;

template <class T>
class CProxy_IATLFlxGrdEvents : public IConnectionPointImpl<T, &__uuidof(_IATLFlxGrdEvents), CComDynamicUnkArray>
{
	// WARNING: This class may be regenerated by the wizard
public:
};
